apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-oss
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: oss
  flexVolume:
    driver: "alicloud/oss"
    options:
      bucket: "maxflink-us"
      url: "oss-us-west-1-internal.aliyuncs.com"
      akId: LTAIK6K5aDNspem1
      akSecret: mARIxPR3pY9WXPhPQVaHDroP809rIE
      otherOpts: "-o max_stat_cache_size=0 -o allow_other"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-oss
spec:
  storageClassName: oss
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
