
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: cluster
    spec:
      containers:
      - name: jobmanager
        image: flink-dummy
        imagePullPolicy: IfNotPresent
        args:
        - cluster
        env:
        - name: FLINK_CLASS
          value: "/f/flink-kubernetes/target/test-classes"
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        volumeMounts:
           - mountPath: /opt/
             name: flink-dist-volume
           - mountPath: /f/
             name: flink-all
      volumes:
          - name: flink-dist-volume
            hostPath:
              path: /flink-root/flink-dist/target/flink-1.7-SNAPSHOT-bin
          - name: flink-all
            hostPath:
              path: /flink-root/
---

apiVersion: v1
kind: Service
metadata:
  name: flink-cluster
spec:
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: query
    port: 6125
  - name: ui
    port: 8081
  selector:
    app: flink
    component: cluster
  externalIPs:
   - 192.168.99.100

