apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-1-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        component: web
    spec:
      containers:
        - name: ngx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  clusterIP: None
